#!/bin/bash

SRC="/Users/emilie/Desktop/training_projects/wanderlust/src"

# ── Phase 2 — Foundation (already done, kept for reference) ──────────────────
# mv "$SRC/styles/theme.js"         "$SRC/styles/theme.ts"
# mv "$SRC/axios.js"                "$SRC/axios.ts"
# mv "$SRC/utils/dateUtils.js"      "$SRC/utils/dateUtils.ts"
# mv "$SRC/utils/sources.js"        "$SRC/utils/sources.ts"
# mv "$SRC/bogusData/bookings.js"   "$SRC/bogusData/bookings.ts"
# mv "$SRC/bogusData/calendar.js"   "$SRC/bogusData/calendar.ts"
# mv "$SRC/bogusData/homes.js"      "$SRC/bogusData/homes.ts"
# mv "$SRC/bogusData/ordersData.js" "$SRC/bogusData/ordersData.ts"
# mv "$SRC/bogusData/skills.js"     "$SRC/bogusData/skills.ts"
# mv "$SRC/bogusData/users.js"      "$SRC/bogusData/users.ts"

# ── Phase 3 — Redux ──────────────────────────────────────────────────────────
# mv "$SRC/store/index.js"                    "$SRC/store/index.ts"
# mv "$SRC/reducers/app.js"                   "$SRC/reducers/app.ts"
# mv "$SRC/reducers/ownerOnboarding.js"       "$SRC/reducers/ownerOnboarding.ts"
# mv "$SRC/actions/addresses.js"              "$SRC/actions/addresses.ts"
# mv "$SRC/actions/bookings.js"               "$SRC/actions/bookings.ts"
# mv "$SRC/actions/calendar.js"               "$SRC/actions/calendar.ts"
# mv "$SRC/actions/dateFormatting.js"         "$SRC/actions/dateFormatting.ts"
# mv "$SRC/actions/layout.js"                 "$SRC/actions/layout.ts"
# mv "$SRC/actions/listings.js"               "$SRC/actions/listings.ts"
# mv "$SRC/actions/monitoring.js"             "$SRC/actions/monitoring.ts"
# mv "$SRC/actions/opinions.js"               "$SRC/actions/opinions.ts"
# mv "$SRC/actions/owners.js"                 "$SRC/actions/owners.ts"
# mv "$SRC/actions/properties.js"             "$SRC/actions/properties.ts"
# mv "$SRC/actions/redirections.js"           "$SRC/actions/redirections.ts"
# mv "$SRC/actions/users.js"                  "$SRC/actions/users.ts"
# mv "$SRC/actions/utils.js"                  "$SRC/actions/utils.ts"

# # ── Phase 4 — Common components ──────────────────────────────────────────────
# mv "$SRC/components/commons/AlertConfirm.jsx"                              "$SRC/components/commons/AlertConfirm.tsx"
# mv "$SRC/components/commons/Button.jsx"                                    "$SRC/components/commons/Button.tsx"
# mv "$SRC/components/commons/Card.jsx"                                      "$SRC/components/commons/Card.tsx"
# mv "$SRC/components/commons/FormFieldWrapper.jsx"                          "$SRC/components/commons/FormFieldWrapper.tsx"
# mv "$SRC/components/commons/GenericCalendar.jsx"                           "$SRC/components/commons/GenericCalendar.tsx"
# mv "$SRC/components/commons/HandmadeCarousel.jsx"                          "$SRC/components/commons/HandmadeCarousel.tsx"
# mv "$SRC/components/commons/ModalNavigation.jsx"                           "$SRC/components/commons/ModalNavigation.tsx"
# mv "$SRC/components/commons/ModulableTableBody.jsx"                        "$SRC/components/commons/ModulableTableBody.tsx"
# mv "$SRC/components/commons/MotionText.jsx"                                "$SRC/components/commons/MotionText.tsx"
# mv "$SRC/components/commons/RedirectionItem.jsx"                           "$SRC/components/commons/RedirectionItem.tsx"
# mv "$SRC/components/commons/SliderCarousel.jsx"                            "$SRC/components/commons/SliderCarousel.tsx"
# mv "$SRC/components/commons/Table.jsx"                                     "$SRC/components/commons/Table.tsx"
# mv "$SRC/components/commons/WrappedFormField.jsx"                          "$SRC/components/commons/WrappedFormField.tsx"
# mv "$SRC/components/commons/modulableTableHeader.jsx"                      "$SRC/components/commons/modulableTableHeader.tsx"
# mv "$SRC/components/commons/basics/Tabs.jsx"                               "$SRC/components/commons/basics/Tabs.tsx"
# mv "$SRC/components/commons/forms/DropZone.jsx"                            "$SRC/components/commons/forms/DropZone.tsx"
# mv "$SRC/components/commons/forms/SwitchItem.jsx"                          "$SRC/components/commons/forms/SwitchItem.tsx"
# mv "$SRC/components/commons/forms/reactUseForm/CostumInput.jsx"            "$SRC/components/commons/forms/reactUseForm/CostumInput.tsx"
# mv "$SRC/components/commons/mainHeader/HeaderCollapsedModal.jsx"           "$SRC/components/commons/mainHeader/HeaderCollapsedModal.tsx"
# mv "$SRC/components/commons/mainHeader/MainHeader.jsx"                     "$SRC/components/commons/mainHeader/MainHeader.tsx"
# mv "$SRC/components/commons/mainHeader/MainHeaderMenu.jsx"                 "$SRC/components/commons/mainHeader/MainHeaderMenu.tsx"
# mv "$SRC/components/commons/mainHeader/MainHeaderTabsContainer.jsx"        "$SRC/components/commons/mainHeader/MainHeaderTabsContainer.tsx"
# mv "$SRC/components/commons/mainHeader/mainHeaderModals/FiltersSearchModal.jsx" "$SRC/components/commons/mainHeader/mainHeaderModals/FiltersSearchModal.tsx"
# mv "$SRC/components/commons/medias/MediaReader.jsx"                        "$SRC/components/commons/medias/MediaReader.tsx"
# mv "$SRC/components/commons/LibraryIntegrations/CloudinaryContainer.jsx"   "$SRC/components/commons/LibraryIntegrations/CloudinaryContainer.tsx"
# mv "$SRC/components/commons/LibraryIntegrations/CloudinaryUploader.jsx"    "$SRC/components/commons/LibraryIntegrations/CloudinaryUploader.tsx"

# # ── Phase 5 — Feature components ─────────────────────────────────────────────
mv "$SRC/components/landing/landingPage.jsx"              "$SRC/components/landing/landingPage.tsx"
mv "$SRC/components/landing/landingPicturesCarousel.jsx"  "$SRC/components/landing/landingPicturesCarousel.tsx"
mv "$SRC/components/landing/landingPolicyHero.jsx"        "$SRC/components/landing/landingPolicyHero.tsx"

mv "$SRC/components/admin/MonitoringModal.jsx"                              "$SRC/components/admin/MonitoringModal.tsx"
mv "$SRC/components/admin/adminSupervisionPanel.jsx"                        "$SRC/components/admin/adminSupervisionPanel.tsx"
mv "$SRC/components/admin/disgrace.jsx"                                     "$SRC/components/admin/disgrace.tsx"
mv "$SRC/components/admin/dormant.jsx"                                      "$SRC/components/admin/dormant.tsx"
mv "$SRC/components/admin/monitoring/AdminMonitoring.jsx"                   "$SRC/components/admin/monitoring/AdminMonitoring.tsx"
mv "$SRC/components/admin/monitoring/MonitoringTableContainer.jsx"          "$SRC/components/admin/monitoring/MonitoringTableContainer.tsx"
mv "$SRC/components/admin/monitoring/TabOptions.jsx"                        "$SRC/components/admin/monitoring/TabOptions.tsx"

mv "$SRC/components/profile/Canvas.jsx"          "$SRC/components/profile/Canvas.tsx"
mv "$SRC/components/profile/profileContent.jsx"  "$SRC/components/profile/profileContent.tsx"
mv "$SRC/components/profile/profileHeader.jsx"   "$SRC/components/profile/profileHeader.tsx"
mv "$SRC/components/profile/profileStep1.jsx"    "$SRC/components/profile/profileStep1.tsx"
mv "$SRC/components/profile/profileStep2.jsx"    "$SRC/components/profile/profileStep2.tsx"
mv "$SRC/components/profile/profileStep3.jsx"    "$SRC/components/profile/profileStep3.tsx"

mv "$SRC/components/ownerflow/AddressesList.jsx"          "$SRC/components/ownerflow/AddressesList.tsx"
mv "$SRC/components/ownerflow/MyAddresses.jsx"            "$SRC/components/ownerflow/MyAddresses.tsx"
mv "$SRC/components/ownerflow/OwnerInformation.jsx"       "$SRC/components/ownerflow/OwnerInformation.tsx"
mv "$SRC/components/ownerflow/addAddress.jsx"             "$SRC/components/ownerflow/addAddress.tsx"
mv "$SRC/components/ownerflow/addAddressForm.jsx"         "$SRC/components/ownerflow/addAddressForm.tsx"
mv "$SRC/components/ownerflow/calendar/OwnerCalendar.jsx" "$SRC/components/ownerflow/calendar/OwnerCalendar.tsx"

mv "$SRC/components/traveller/ratingsOpinions/MediaFieldArray.jsx"    "$SRC/components/traveller/ratingsOpinions/MediaFieldArray.tsx"
mv "$SRC/components/traveller/ratingsOpinions/RatingForm.jsx"          "$SRC/components/traveller/ratingsOpinions/RatingForm.tsx"
mv "$SRC/components/traveller/ratingsOpinions/SomeFormContainer.jsx"   "$SRC/components/traveller/ratingsOpinions/SomeFormContainer.tsx"
mv "$SRC/components/traveller/ratingsOpinions/StarFormField.jsx"       "$SRC/components/traveller/ratingsOpinions/StarFormField.tsx"
mv "$SRC/components/traveller/ratingsOpinions/TaggedUsersFieldArray.jsx" "$SRC/components/traveller/ratingsOpinions/TaggedUsersFieldArray.tsx"

mv "$SRC/components/listings/PropertiesFieldArrayForListing.jsx" "$SRC/components/listings/PropertiesFieldArrayForListing.tsx"
mv "$SRC/components/listings/RoomsFieldArrayForListing.jsx"      "$SRC/components/listings/RoomsFieldArrayForListing.tsx"
mv "$SRC/components/listings/SkillsFieldArrayForListing.jsx"     "$SRC/components/listings/SkillsFieldArrayForListing.tsx"
mv "$SRC/components/listings/createListingContainer.jsx"         "$SRC/components/listings/createListingContainer.tsx"
mv "$SRC/components/listings/createListingForm.jsx"              "$SRC/components/listings/createListingForm.tsx"

mv "$SRC/components/animationsInProgress/AnimationsContainer.jsx"              "$SRC/components/animationsInProgress/AnimationsContainer.tsx"
mv "$SRC/components/animationsInProgress/CandleAnim.jsx"                       "$SRC/components/animationsInProgress/CandleAnim.tsx"
mv "$SRC/components/animationsInProgress/CandleAnimSpring.jsx"                 "$SRC/components/animationsInProgress/CandleAnimSpring.tsx"
mv "$SRC/components/animationsInProgress/CollapsibleContainer.jsx"             "$SRC/components/animationsInProgress/CollapsibleContainer.tsx"
mv "$SRC/components/animationsInProgress/FlowerAndCat.jsx"                     "$SRC/components/animationsInProgress/FlowerAndCat.tsx"
mv "$SRC/components/animationsInProgress/FishesAndCat/FishAndCat.jsx"          "$SRC/components/animationsInProgress/FishesAndCat/FishAndCat.tsx"
mv "$SRC/components/animationsInProgress/FishesAndCat/Monkey.jsx"              "$SRC/components/animationsInProgress/FishesAndCat/Monkey.tsx"
mv "$SRC/components/animationsInProgress/FishesAndCat/MonkeyHand.jsx"          "$SRC/components/animationsInProgress/FishesAndCat/MonkeyHand.tsx"
mv "$SRC/components/animationsInProgress/FishesAndCat/OneFish.jsx"             "$SRC/components/animationsInProgress/FishesAndCat/OneFish.tsx"

mv "$SRC/components/testsForCanvas/CanvasBoard.jsx"   "$SRC/components/testsForCanvas/CanvasBoard.tsx"
mv "$SRC/components/testsForCanvas/CanvasHandler.jsx" "$SRC/components/testsForCanvas/CanvasHandler.tsx"

# # ── Phase 6 — Root ───────────────────────────────────────────────────────────
# mv "$SRC/components/Calendar.jsx"                  "$SRC/components/Calendar.tsx"
# mv "$SRC/components/CalendarBody.jsx"              "$SRC/components/CalendarBody.tsx"
# mv "$SRC/components/DateToggler.jsx"               "$SRC/components/DateToggler.tsx"
# mv "$SRC/components/Footer.jsx"                    "$SRC/components/Footer.tsx"
# mv "$SRC/components/HandmadeCalendarContainer.jsx" "$SRC/components/HandmadeCalendarContainer.tsx"
# mv "$SRC/components/Header.jsx"                    "$SRC/components/Header.tsx"
# mv "$SRC/components/Home.jsx"                      "$SRC/components/Home.tsx"
# mv "$SRC/components/ModalHome.jsx"                 "$SRC/components/ModalHome.tsx"
# mv "$SRC/components/ModalProfile.jsx"              "$SRC/components/ModalProfile.tsx"
# mv "$SRC/components/PerspectiveCarousel.jsx"       "$SRC/components/PerspectiveCarousel.tsx"
# mv "$SRC/components/Test.jsx"                      "$SRC/components/Test.tsx"
# mv "$SRC/components/View.jsx"                      "$SRC/components/View.tsx"
# mv "$SRC/hooks.jsx"                                "$SRC/hooks.ts"
# mv "$SRC/ProtectedAdminRoute.jsx"                  "$SRC/ProtectedAdminRoute.tsx"
# mv "$SRC/ProtectedConnectedRoute.jsx"              "$SRC/ProtectedConnectedRoute.tsx"
# mv "$SRC/ProtectedOwnerRoute.jsx"                  "$SRC/ProtectedOwnerRoute.tsx"
# mv "$SRC/App.jsx"                                  "$SRC/App.tsx"
# mv "$SRC/main.jsx"                                 "$SRC/main.tsx"

echo "✅ Done"
