/** MODALS */

/** OWNER CENTRAL MODALS */

export const CENTRAL_MODAL_HEIGHT = 600;
export const CENTRAL_MODAL_WIDTH = 800;

export const CENTRAL_MODAL_CONTENT_HEIGHT = 500;

export const CENTRAL_MODAL_HEADER_HEIGHT = 50;


/** TRAVELLER RIGHT MODALS */